/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mgmtsys.gui;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mgmtsys.dao.AddPatientdao;
import mgmtsys.dao.Bedmanagedao;
import mgmtsys.dao.UpdateDoctordao;
import mgmtsys.dao.UpdatePatientdao;
import mgmtsys.po.BedmanagePo;
import mgmtsys.po.PatientPO;

/**
 *
 * @author welcome
 */
public class UpdatePatient extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePatient
     */
    public UpdatePatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        Heading = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        per_lab = new javax.swing.JLabel();
        phval_lab = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        FName_Validation = new javax.swing.JLabel();
        age_Validation_Texrt = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(80, 113, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Patient Id");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 85, 27));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Full Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Phone NO.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 105, -1));

        jLabel91.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel91.setText("Blood Group");
        jPanel2.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel61.setText("Address");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Gender");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 84, -1));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 249, 32));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 140, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 242, 50));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 164, 30));

        Heading.setBackground(new java.awt.Color(255, 153, 153));
        Heading.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Update Covid Patient Details");
        Heading.setOpaque(true);
        jPanel2.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 56));

        jButton3.setBackground(new java.awt.Color(0, 51, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/cancel.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 145, 35));

        jButton4.setBackground(new java.awt.Color(0, 51, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/search.png"))); // NOI18N
        jButton4.setText("View");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 149, 36));

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home Isolation", "General", "Icu" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Age");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 118, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Percentage of Positivity");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 190, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Bed");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 50, -1));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 30));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 118, 30));

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 100, -1));

        per_lab.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        per_lab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(per_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 410, 380, 20));

        phval_lab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        phval_lab.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(phval_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 250, 20));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/search.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/update.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        FName_Validation.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        FName_Validation.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(FName_Validation, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 250, 20));

        age_Validation_Texrt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        age_Validation_Texrt.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(age_Validation_Texrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 180, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 930, 560));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/Backframe.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        //check positivity percentage.
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            int p=Integer.parseInt(jTextField5.getText());
            if(p>0 && p<=20)
            {
                per_lab.setText("Hospital prefer you for Home Isolation");
            }
            else if(p>20 && p<=50)
            {
                per_lab.setText("Hospital prefer you for General Bed");
            }
            else
            {
                per_lab.setText("Hospital prefer you for Icu Bed");
            }
        }
        else
        {
            per_lab.setText("**!Invalide Input!**");
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped

    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
     
    }//GEN-LAST:event_jTextField1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // clear all
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField4.setText("");
        jTextArea1.setText("");
        //  jTextField5.setText("");
        jTextField1.setText("");
//        jTextField8.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //view patient table
        ViewPatient vpt=new ViewPatient();
        vpt.setVisible(true);
        vpt.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String perpos=(String)jComboBox2.getSelectedItem();
        PatientPO ptpo=new PatientPO();
        ptpo.setBed(perpos);
        if(perpos.equals("General"))
        {
            try {
                String rs=AddPatientdao.checkgeneral(ptpo);
                BedmanagePo bmpo=new BedmanagePo();
                Bedmanagedao.tGeneral(bmpo);
                String tgeneral=bmpo.gettGeneral();//total general beds in hospital
                if((Integer.parseInt(rs))>=(Integer.parseInt(tgeneral)))
                {
                    JOptionPane.showMessageDialog(null,rs+" General Beds are Booked Already");
                    jComboBox2.removeItemAt(1);
                }
            } catch (Exception ex) {
                Logger.getLogger(AddPatient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(perpos.equals("Icu"))
        {
            try {
                String rs=AddPatientdao.checkicu(ptpo);
                if(Integer.parseInt(rs)>10)
                {
                    JOptionPane.showMessageDialog(null,rs+"Beds of Icu are Booked Already");
                    jComboBox2.removeItemAt(2);
                }
            } catch (Exception ex) {
                Logger.getLogger(AddPatient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
   // Accept only phone correct number
        String phoneno=jTextField3.getText();
        int length=phoneno.length();
        char c=evt.getKeyChar();
        //check for number.
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check length not more than 10
            if(length<10)
            {
                jTextField3.setEditable(true);
                  phval_lab.setText("");
            }
            else{
                jTextField3.setEditable(false);
//               Validation_Texrt.setText("Enter Valid Phone Number");
            }
          
        }
          else{
                    if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                        jTextField3.setEditable(true);
                      phval_lab.setText("");
                    }
                    else
                    {
                            jTextField4.setEditable(false);
                           phval_lab.setText("Enter Valid Phone Number");
                    }
                        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminOptions ado=new AdminOptions();
        ado.setVisible(true);
        ado.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //1.get values from textfieldssearch data from specified id.
        PatientPO udpo=new PatientPO();
        String id;
        id=jTextField1.getText().trim();
        if(id!=null)
        {
            udpo.setP_id(id);
            String rest=UpdatePatientdao.upfetchpPatient(udpo);
            if(rest!=null){
                jTextField2.setText(udpo.getFname());
                jTextField3.setText(udpo.getContactno());
                jTextField4.setText(udpo.getAge());
                jTextField5.setText(udpo.getPerpos());
                jTextArea1.setText(udpo.getAddress());
                jComboBox1.setSelectedItem(udpo.getGender());
//                jComboBox2.setSelectedItem(udpo.getBed());
                jComboBox3.setSelectedItem(udpo.getBldgrp());
            }else
            {
                JOptionPane.showMessageDialog(null,"Record not found with Id -->"+id,"Opps",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
       String p_id;
        String fname;
        String contactno;
        String gender;
        String address;   
        String age;
        String  perpos;
        String  bldgrp;
        String bed;
        p_id=jTextField1.getText().trim();
           if(jTextField1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Search the Patient Id First");
        }
             else{
        PatientPO udpp=new  PatientPO();
             fname=jTextField2.getText();
        contactno=jTextField3.getText();
        age=jTextField4.getText();
        perpos=jTextField5.getText();
        address=jTextArea1.getText();
        gender=(String)jComboBox1.getSelectedItem();
        bed=(String)jComboBox2.getSelectedItem();
        bldgrp=(String)jComboBox3.getSelectedItem();
    if(fname.isEmpty()||contactno.isEmpty()||address.isEmpty()||age.isEmpty()|| bldgrp.isEmpty()||perpos.isEmpty()||gender.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Fill the Information Properly!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
              PatientPO ptpo=new PatientPO();
            ptpo.setP_id(p_id);
            ptpo.setFname(fname);
            ptpo.setContactno(contactno);
              ptpo.setAddress(address);
              ptpo.setAge(age);
             ptpo.setPerpos(perpos);
             ptpo.setBldgrp(bldgrp);
             ptpo.setBed(bed);
              ptpo.setGender(gender);
            int rest=UpdatePatientdao.updatePatient(ptpo);
            if(rest!=0){
                JOptionPane.showMessageDialog(null,"1 Record Updated With PatientId: "+p_id,"Update SuccessFull!",JOptionPane.INFORMATION_MESSAGE);
                        }
        }} }catch (Exception ex) {
            Logger.getLogger(UpdateDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        //check the name
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || evt.getExtendedKeyCode() == KeyEvent.VK_CAPS_LOCK || evt.getExtendedKeyCode() == KeyEvent.VK_SPACE){
            jTextField2.setEditable(true);
             FName_Validation.setText("");
        }
        else{
              jTextField2.setEditable(false);
              FName_Validation.setText("Enter Valid Name");
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // age always in number
          if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                        jTextField4.setEditable(true);
                          age_Validation_Texrt.setText("");
       }
       else if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                            jTextField4.setEditable(true);
                         age_Validation_Texrt.setText("");
                       
                    }
                    else
                    {
                      jTextField4.setEditable(false);
                             age_Validation_Texrt.setText("Enter Valid Age");
                    }
    }//GEN-LAST:event_jTextField4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FName_Validation;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel age_Validation_Texrt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel per_lab;
    private javax.swing.JLabel phval_lab;
    // End of variables declaration//GEN-END:variables
}
