/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mgmtsys.gui;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mgmtsys.dao.UpdateDoctordao;
import mgmtsys.po.DoctorPO;

/**
 *
 * @author welcome
 */
public class UpdateDoctor extends javax.swing.JFrame {
    public UpdateDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Validation_Texrt = new javax.swing.JLabel();
        FName_Validation = new javax.swing.JLabel();
        LName_Validation = new javax.swing.JLabel();
        sal_Validation_Texrt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(80, 113, 199));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/Backframe.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Doctor Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 78, 85, 27));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 156, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Phone NO.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, 105, -1));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel71.setText("Joining Date");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 304, -1, -1));

        jLabel91.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel91.setText("Sallary");
        jPanel1.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 84, -1));

        jLabel81.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel81.setText("Specialist In");
        jPanel1.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 395, 105, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel61.setText("Address");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 311, 98, -1));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 79, 124, 27));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 249, 32));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 153, 249, 31));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 218, 252, 30));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 295, 242, 50));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 392, 249, 32));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 241, 32));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/update.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 151, 35));

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Update Doctor");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 926, 56));

        jButton3.setBackground(new java.awt.Color(0, 51, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/cancel.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 145, 35));

        jDateChooser1.setDateFormatString("MM dd, yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 295, 241, 41));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/search.png"))); // NOI18N
        jButton4.setText("View");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 149, 36));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 231, 84, -1));

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 227, 118, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttons/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 78, -1, 28));

        Validation_Texrt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        Validation_Texrt.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(Validation_Texrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 263, 252, 25));

        FName_Validation.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        FName_Validation.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(FName_Validation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 240, 20));

        LName_Validation.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        LName_Validation.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(LName_Validation, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 250, 20));

        sal_Validation_Texrt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        sal_Validation_Texrt.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(sal_Validation_Texrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 240, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
 
    }//GEN-LAST:event_jTextField4ActionPerformed
                             
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
         String id;
         String fname;
         String lname;
        String contactno;
        String address;
        String joiningdate;
        String specialistin;
        String sallary;
         String gender;
         id=jTextField1.getText().trim();
           if(jTextField1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Search the DoctorId First");
        }
         else{
         DoctorPO udpo=new DoctorPO();
        fname=jTextField2.getText();
        lname=jTextField3.getText();
        contactno=jTextField4.getText();
        address=jTextArea1.getText();
        SimpleDateFormat dformat1;
        dformat1 = new SimpleDateFormat("yyyy--MM--dd");
        joiningdate=(dformat1.format(jDateChooser1.getDate()));
        specialistin=jTextField5.getText();
        sallary=jTextField6.getText();
        gender=(String)jComboBox1.getSelectedItem();
        if(fname.isEmpty()||lname.isEmpty()||contactno.isEmpty()||address.isEmpty()||specialistin.isEmpty()||sallary.isEmpty()||gender.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Fill the Information Properly!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
         udpo.setId(id);
         udpo.setId(id);
        udpo.setFname(fname);
        udpo.setLname(lname);
        udpo.setContactno(contactno);
        udpo.setAddress(address);
        udpo.setJoiningdate(joiningdate);
        udpo.setSpecialistin( specialistin);
         udpo.setSallary(sallary);
         udpo.setGender(gender);
            int rest=UpdateDoctordao.updateDoctor(udpo);
            if(rest!=0){
                JOptionPane.showMessageDialog(null,"1 Record Updated With DoctorId : "+id,"Update SuccessFull!",JOptionPane.INFORMATION_MESSAGE);
                        }
        }} }catch (Exception ex) {
            Logger.getLogger(UpdateDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // clear all
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextArea1.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //      1.get values from textfieldssearch data from specified id.
       DoctorPO udpo=new DoctorPO();
        String id;
        id=jTextField1.getText().trim();
        if(id!=null)
        {
          udpo.setId(id);
          String rest=UpdateDoctordao.upfetchDoctor(udpo);
          if(rest!=null){
           jTextField2.setText(udpo.getFname());
           jTextField3.setText(udpo.getLname());
           jTextField4.setText(udpo.getContactno());
           jComboBox1.setSelectedItem(udpo.getGender());
           jTextArea1.setText(udpo.getAddress());
           SimpleDateFormat dformat1;
          dformat1 = new SimpleDateFormat("yyyy--MM--dd");
              try {
                  jDateChooser1.setDate(dformat1.parse((udpo.getJoiningdate())));
              } catch (ParseException ex) {
                  Logger.getLogger(UpdateDoctor.class.getName()).log(Level.SEVERE, null, ex);
              }
            jTextField5.setText( udpo.getSpecialistin());
            jTextField6.setText(udpo.getSallary());  
         }else 
         {
             JOptionPane.showMessageDialog(null,"Record not found with Id -->"+id,"Opps",JOptionPane.WARNING_MESSAGE);
         }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AdminOptions ado=new AdminOptions();
        ado.setVisible(true);
        ado.show();
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // Open ViewDoctors FRAME
        ViewDoctor vd=new ViewDoctor();
        vd.setVisible(true);
        vd.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        //check the name
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || evt.getExtendedKeyCode() == KeyEvent.VK_CAPS_LOCK){
            jTextField2.setEditable(true);
             FName_Validation.setText("");
        }
        else{
              jTextField2.setEditable(false);
              FName_Validation.setText("Enter Valid Name");
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
       //check the name
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || evt.getExtendedKeyCode() == KeyEvent.VK_CAPS_LOCK){
            jTextField3.setEditable(true);
             LName_Validation.setText("");
        }
        else{
              jTextField3.setEditable(false);
              LName_Validation.setText("Enter Valid Name");
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
  // Accept only phone correct number
        String phoneno=jTextField4.getText();
        int length=phoneno.length();
        char c=evt.getKeyChar();
        //check for number.
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check length not more than 10
            if(length<10)
            {
                jTextField4.setEditable(true);
                   Validation_Texrt.setText("");
            }
            else{
                jTextField4.setEditable(false);
//               Validation_Texrt.setText("Enter Valid Phone Number");
            }
          
        }
          else{
                    if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                        jTextField4.setEditable(true);
                         Validation_Texrt.setText("");
                    }
                    else
                    {
                            jTextField4.setEditable(false);
                             Validation_Texrt.setText("Enter Valid Phone Number");
                    }
                        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
   //SALARY SHOULD BE IN NUMBER
       if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                        jTextField6.setEditable(true);
                         sal_Validation_Texrt.setText("");
       }
       else if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                            jTextField6.setEditable(true);
                         sal_Validation_Texrt.setText("");
                       
                    }
                    else
                    {
                        jTextField6.setEditable(false);
                             sal_Validation_Texrt.setText("Enter Salary In Number");
                    }
    }//GEN-LAST:event_jTextField6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FName_Validation;
    private javax.swing.JLabel LName_Validation;
    private javax.swing.JLabel Validation_Texrt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel sal_Validation_Texrt;
    // End of variables declaration//GEN-END:variables
}
